### ISSUE TITLE
Show field's data instead of data

### ISSUE THREAD

**Issue by GitMensch** [OlegKunitsyn/gnucobol-debug#4] opened 2020-04-23 06:08 UTC
With the sample shown in the screenshot the code generation (sample.c.l.h) looks something like (faked, please include your samples in this repository):

```c
/* Data storage */
static cob_u8_t	b_8[2] __attribute__((aligned));	/* WS-NUMERIC */
static cob_u8_t	b_9[5] __attribute__((aligned));	/* WS-SIGNED-DECIMAL */
...
static cob_u8_t	b_13[23] __attribute__((aligned));	/* WS-GROUP */
static cob_u8_t	b_30[2] __attribute__((aligned));	/* WS-CHECK */

...

/* Fields */
static cob_field f_8	= {2, b_8, &a_1};	/* WS-NUMERIC */
static cob_field f_9	= {6, b_9, &a_2};	/* WS-SIGNED-DECIMAL */
static cob_field f_13	= {2, b_13, &a_3};	/* WS-GROUP */
static cob_field f_15	= {2, b_14 + 4, &a_3};	/* WS-GROUP-NUMERIC */
static cob_field f_16	= {5, b_14 + 6, &a_3};	/* WS-GROUP-SIGNED-DECIMAL */
static cob_field f_17	= {5, b_14 + 8, &a_3};	/* WS-GROUP-UNSIGNED-DECIMAL */
static cob_field f_18	= {6, b_14 + 10, &a_3};	/* WS-GROUP-ALPHABETIC */
static cob_field f_19	= {5, b_14 + 12, &a_3};	/* WS-GROUP-ALPHANUMERIC */
static cob_field f_20	= {2, b_20, &a_1};	/* WS-CHECK  */
```

The plugin currently shows the entries in the data storage, especially as this won't work for all kinds of storage - is there any option to show the fields [include data pointer and length] instead?

**Comment by brunopacheco1** [comment] 2020-04-23 14:51
`
/* Program local variables for 'PETSTORE' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;

/* Decimal structures */
	cob_decimal	*d0 = NULL;
	cob_decimal	*d1 = NULL;


/* Subscripts */
int		i0;

/* Local cob_field items */
cob_field		f0;


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_6[2900] __attribute__((aligned));	/* WS-ITEM */
static int	b_7;	/* I */
static cob_u8_t	b_12[17] __attribute__((aligned));	/* WS-BILL */
static cob_u8_t	b_16[8] __attribute__((aligned));	/* WS-CONTROL */
static cob_u8_t	b_22[50] __attribute__((aligned));	/* HEADING-LINE1 */
static cob_u8_t	b_30[50] __attribute__((aligned));	/* HEADING-LINE2 */
static cob_u8_t	b_38[50] __attribute__((aligned));	/* ITEM-LINE */
static cob_u8_t	b_46[50] __attribute__((aligned));	/* TOTAL-LINE1 */
static cob_u8_t	b_49[50] __attribute__((aligned));	/* TOTAL-LINE2 */
static cob_u8_t	b_54[50] __attribute__((aligned));	/* TOTAL-LINE3 */
static cob_u8_t	b_59[50] __attribute__((aligned));	/* TOTAL-LINE4 */

/* End of data storage */


/* Fields */
static cob_field f_13	= {3, b_12, &a_4};	/* TOTAL-QUANTITY */
static cob_field f_14	= {7, b_12 + 3, &a_5};	/* TOTAL-COST */
static cob_field f_15	= {7, b_12 + 10, &a_5};	/* TOTAL-COST-DISCOUNTED */
static cob_field f_17	= {3, b_16, &a_4};	/* J */
static cob_field f_18	= {1, b_16 + 3, &a_6};	/* DISCOUNT */
static cob_field f_19	= {3, b_16 + 4, &a_4};	/* MINIMUM-FOR-DISCOUNT */
static cob_field f_20	= {1, b_16 + 7, &a_2};	/* USER-ANSWER */
static cob_field f_22	= {50, b_22, &a_7};	/* HEADING-LINE1 */
static cob_field f_30	= {50, b_30, &a_7};	/* HEADING-LINE2 */
static cob_field f_38	= {50, b_38, &a_7};	/* ITEM-LINE */
static cob_field f_39	= {16, b_38, &a_2};	/* DETAIL-DESCRIPTION */
static cob_field f_41	= {10, b_38 + 18, &a_9};	/* DETAIL-PRICE */
static cob_field f_43	= {8, b_38 + 30, &a_10};	/* DETAIL-QUANTITY */
static cob_field f_45	= {10, b_38 + 40, &a_9};	/* DETAIL-COST */
static cob_field f_46	= {50, b_46, &a_7};	/* TOTAL-LINE1 */
static cob_field f_49	= {50, b_49, &a_7};	/* TOTAL-LINE2 */
static cob_field f_53	= {10, b_49 + 40, &a_11};	/* DET-TOTAL-QUANTITY */
static cob_field f_54	= {50, b_54, &a_7};	/* TOTAL-LINE3 */
static cob_field f_58	= {10, b_54 + 40, &a_9};	/* DET-TOTAL-COST */
static cob_field f_59	= {50, b_59, &a_7};	/* TOTAL-LINE4 */
static cob_field f_63	= {10, b_59 + 40, &a_9};	/* DET-TOTAL-DISCOUNTED */

/* End of fields */

`

**Comment by brunopacheco1** [comment] 2020-05-02 20:11
@GitMensch I was taking a look at this issue, just to learn a bit more about the code of this extension and all the rest (GC, C, GDB), and it seems to be possible adding the fields in replacement of the data storage fields, but GC is not adding all fields to l.h file (header file?).

In the sample I have provided before, the fields related to the group WS-ITEM, which is a table or an array, were totally ignored. Do you know if it is possible adding them to the c code or this is not supported at all by GC?

**Comment by GitMensch** [comment] 2020-05-02 21:57
> Do you know if it is possible adding them to the c code or this is not supported at all by GC?

I don't remember an old option to generate all (even the ones not directly referenced), but `-fdump=ALL` (only available with 3.1+) will lead to all fields being generated.

**Comment by brunopacheco1** [comment] 2020-05-03 15:06
So, I was hacking around adding the fields in replacement of data storage, it looks much better.

I could finish these changes to present the variables, but then we have an issue with displaying all of them. It has worked as you mentioned on GC 3.1, after adding `-fdump=ALL` all missing variables were presented correctly, but if there isn't this option on GC 2.2, how should we proceed?

I checked the GC 2.2 options but I couldn't find anything useful.

@GitMensch any idea? Perhaps this missing field issue is only related to TABLE's?
@OlegKunitsyn Do you think these fix should be done? Maybe adding one description on README about it?

**Comment by GitMensch** [comment] 2020-05-03 15:16
You'll have any fields referenced available, this may be reasonable enough.
In any case: just add an option in the json configuration to use either the new field based logic or the old data-pointer only reference.
This way everyone is free to use either one (and people with 3.1 have the option to use it together with the additional dump).

**Comment by OlegKunitsyn** [comment] 2020-05-04 05:10
I've pushed 'fields' branch that includes cobc version. Feel free to hack.

**Comment by brunopacheco1** [comment] 2020-05-04 14:28
Great, thanks. I'll check this out.

**Comment by brunopacheco1** [comment] 2020-05-04 15:23
@OlegKunitsyn what is the idea, based on the user's versions the "dump all" option is added automatically? But we keep the old logic for GC 2.2 as suggested by @GitMensch ?

**Comment by OlegKunitsyn** [comment] 2020-05-04 15:41
I would keep old logic, yes. `this.cobcver`equals `22` for GC 2.2 for now. If the major number i.e. 2 or 3 is enough for compatibility, please fix line 17 in `extension.ts`.

**Comment by GitMensch** [comment] 2020-05-04 15:44
According to GnuCOBOL's NEWS file you need 3.0+ for `-fdump` (it is also available in 3.1 and 4.0, but not in 2.2 or earlier versions).

**Comment by brunopacheco1** [comment] 2020-05-05 21:12
@OlegKunitsyn I need some support on parsing and presenting the variables on the debugger panel.

So, my idea was to present in the panel the data storages and the fields (what we can get or everything if it is 3+), regardless of the GC version, hierarchically as it is defined in the COBOL file.

I have done some changes in the way the C file is parsed, so now all data storages and fields are loaded in memory as intended. The petstore sample has the following output:

`
RETURN-CODE > b_2:
	
WS-ITEM > b_8:
	ITEM-DESCRIPTION > f_10
	ITEM-PRICE > f_11
	ITEM-QUANTITY > f_12
	ITEM-COST > f_13
	
I > b_9:
	
WS-BILL > b_14:
	TOTAL-QUANTITY > f_15
	TOTAL-COST > f_16
	TOTAL-COST-DISCOUNTED > f_17
	
WS-CONTROL > b_18:
	J > f_19
	DISCOUNT > f_20
	MINIMUM-FOR-DISCOUNT > f_21
	USER-ANSWER > f_22
	
HEADING-LINE1 > b_24:
	
HEADING-LINE2 > b_32:
	
ITEM-LINE > b_40:
	DETAIL-DESCRIPTION > f_41
	DETAIL-PRICE > f_43
	DETAIL-QUANTITY > f_45
	DETAIL-COST > f_47
	
TOTAL-LINE1 > b_48:
	
TOTAL-LINE2 > b_51:
	DET-TOTAL-QUANTITY > f_55
	
TOTAL-LINE3 > b_56:
	DET-TOTAL-COST > f_60
	
TOTAL-LINE4 > b_61:
	DET-TOTAL-DISCOUNTED > f_65
`

Now the problem is how to map everything to be presented on the panel. The current code I have in my fork is switching from data storages to fields depending on GC version, but I believe presenting everything could be more beneficial, what do you think?

**Comment by GitMensch** [comment] 2020-05-05 21:42
Especially for big programs you'll have megabytes of variables, something in the range of 100-500 is not seldom and it can be much more. So in any case I suggest to have at least an option to specify "all variables" or "current variables".
Ideally this would be done in a way you could toggle between "local variables" (all shown with sub-items)  and "focused/current variables" (only those that are part of the current statement (those referenced in the current C instruction (like `memcpy`, `cob_display`, ...).

A sample for the first one (ignore the mainframe part in the beginning ;-) :
![all variables - as tree](https://raw.githubusercontent.com/BroadcomMFD/debugger-for-mainframe/7cd54eb0d348ba8d3e575dc92e114c46f77d83d3/Breakpoints.gif)

A sample for the second one:
![current variables](https://raw.githubusercontent.com/RechInformatica/rech-cobol-debugger/0cc1ca8280ec8986c8cb2a1df7eb06eb8e0375e9/images/rech-cobol-debugger-usage.gif)

**Comment by OlegKunitsyn** [comment] 2020-05-06 14:19
@brunopacheco1 just pushed the parsing of fields and numeric cobc version. Enjoy.

**Comment by GitMensch** [comment] 2020-05-06 15:06
@OlegKunitsyn Is there currently a reason to not push this to master? I *guess* the screenshot needs some update some day, too.

**Comment by brunopacheco1** [comment] 2020-05-06 15:27
There's some work to do still, let me see what I can do this evening.

**Comment by GitMensch** [comment] 2020-05-06 19:13
@brunopacheco1 Thank you for working on this. I guess you're pulling @OlegKunitsyn changes in your field branch, finish it until we have at least a nice working state (software can always improve) and PR to master back.
Take your time, it would be marvelous if you reach this state in the next days, not even thinking of this evening!

Again: Thanks to both of you!

**Comment by OlegKunitsyn** [comment] 2020-05-08 05:10
TypeError: Cannot read property 'vars' of undefined.
Failed on sample.cbl with `"group": ["subsample.cbl","subsubsample.cbl"]`cobc 2.2

**Comment by brunopacheco1** [comment] 2020-05-08 07:52
Sorry, my bad, I lost some code when I created the PR, but I just have pushed the fix and other changes.

I am reusing the Variable interface everywhere on mi2.ts. The data storages and fields are parsed and stored together, not it a matter of properly converter them into a VS Debugger Variable.

I've noticed that there's a bug on the parser from GDB value into Object, we cannot just rely on the cob_field.data, it's a C structure and it looks is already bringing the pointer, the data storage value and the size. But the current parser is all the time building the object and doing an evalExpression on VARIABLE.data, but it should just bring the data value, instead.

The field's data value is something like:
`{size = 16, data = 0x55555555b490 <b_8> ' ' <repeats 16 times>, '0' <repeats 13 times>, ' ' <repeats 16 times>, '0' <repeats 13 times>, ' ' <repeats 16 times>, '0' <repeats 13 times>, ' ' <repeats 16 times>, '0' <repeats 13 times>, ' ' <repeats 16 times>, '0' <repeats 13 times>, ' ' <repeats 16 times>, '0' <repeats 13 times>, ' ' <repeats 16 times>, \"0000000000\"..., attr = 0x5555555590b0 <a_2>}`

Everything after `<b_8>` is the DS value, size looks like the last index, so possibly we just have to do a substring from 0 to size, or a substring until the next comma. I'll try that out.

**Comment by GitMensch** [comment] 2020-05-08 08:15
>  size looks like the last index

Nearly correct: its the size, so the last index is size-1, but otherwise correct.

Note: you can also have variable sized fields (and also variable data pointers). You may want to check with a field definition that comes from:

```cobol
       LINKAGE SECTION.
       77 SOMEVAR PIC X ANY LENGTH.
       PROCEDURE DIVISION USING SOMEVAR.
```

**Comment by brunopacheco1** [comment] 2020-05-08 08:35
Thanks for your samples, let's check them. About the size, usually on substring methods the last index is not inclusive, so the result is going to be 0 to size - 1, in the end.

On Friday, May 8, 2020, 10:16 AM, Simon Sobisch <notifications@github.com> wrote:





size looks like the last index


Nearly correct: its the size, so the last index is size-1, but otherwise correct.

Note: you can also have variable sized fields (and also variable data pointers). You may want to check with a field definition that comes from:
       LINKAGE SECTION.
       77 SOMEVAR PIC X ANY LENGTH.
       PROCEDURE DIVISION USING SOMEVAR.

**Comment by OlegKunitsyn** [comment] 2020-05-08 09:13
The code is not compiling anymore. 
`Property 'name' does not exist on type 'Variable'.`
Please test before pushing.

**Comment by brunopacheco1** [comment] 2020-05-08 21:39
I pushed some small changes to see the behavior of the fields' values and I have got some interesting answers.

They are by default initialized which I supposed they were not.

The response for fields during `evalExpression` returns the correspondent data storage value and a size. The value looks like "'0' <repeats 13 times>, ' ' <repeats 8 times>". When a 100 is inserted into a field of size 3 in the beginning of this sample data storage, instead of returning "1000000000000, ' ' <repeats 8 times>", GDB is going to return ""\"1\"'0' <repeats 12 times>, ' ' <repeats 8 times>". 😄 

So the substring is not going to work properly in this case. My ideas are:
* Replace during the evaluation this <repeats ...> to the actual values (it's not good because it may return many different patterns like that in the same response like the sample above);
* Find an option on GC to return the values as they should be (e.g. "0000000000000" instead of '0' <repeats 13 times>). I believe this is the ideal solution. @GitMensch do you have an idea on how to workaround on that?

Another thing I have noticed is, the GDB eval-expression has a limit of characters, there's a data storage of 2900 chars in the petstore sample, when calling its value, the response is truncated.

@OlegKunitsyn Is there an option to avoid that? Perhaps eval-expression is not the ideal method to get the values for the variables.

**Comment by GitMensch** [comment] 2020-05-08 22:07
> Perhaps eval-expression is not the ideal method to get the values for the variables.

I think it is reasonable for the preview (think of a tooltip you hover over a variable in the code area) of items being `USAGE DISPLAY`. For a "real" display and especially for an accept into the data later this is likely the wrong option.

It must be possible to display the data directly somehow, if I remember correctly `print data-array-ptr` would show the full data...

A workaround would be to `call` a function in libcob (which is guaranteed to be loaded already and its public functions start all with a `cob_` prefix so conflicts are unlikely) that returns the value, this would also help with `USAGE COMP-...` items (the other option is that this plugin also implements the conversion [should be not too hard] from the attributes the cob_field references).

Those functions don't exist in GnuCOBOL yet (*may* could get into the upcoming 3.1rc1) a rough draft was already done, something like:

```c
char * cob_print_field(cob_field *);
char * cob_print_refmod(cob_field *,size_t, size_t);
void cob_set_field(cob_field *, char *);
void cob_set_refmod(cob_field *,size_t, size_t);
```
with a sample use of
```c
	call cob_print_field (0x012b4e)
	  	"0.123E-4"
	call cob_print_field (0x018e5e)
	  	"place big lorem ipsum here with 4 MBs d-...
	call cob_print_refmod (0x018e5e, 2,10)
	  	"lace big l"
```

Would this be useful? In any case it would be a 3.1+ only function so this would mean to keep another option which is chosen depending on the availability of this function.

What do you think?

Can the "show data" and "enter data" parts of the debugging ui be adjusted to call a method instead of directly setting the field?

**Comment by brunopacheco1** [comment] 2020-05-10 15:44
About calling functions, I believe it is possible with `data-evaluate-expression`, if the functions are globally loaded and accessible.

But for the current problem, this is not going to help, unfortunately.

> It must be possible to display the data directly somehow, if I remember correctly `print data-array-ptr` would show the full data...

Where this option should be, on GC? I have found this `set print array on` on GDB, but it didn't work, the value keeps coming `'0' <repeats 13 times>, ' ' <repeats 8 times>`.

**Comment by GitMensch** [comment] 2020-05-10 15:55
> Where this option should be, on GC? 

I meant to print via GDB, there isn't an function like this in GnuCOBOL. maybe https://stackoverflow.com/questions/29528732/gdb-print-all-values-in-char-array helps?

**Comment by brunopacheco1** [comment] 2020-05-10 16:06
Oh, I tried that one as well, I forgot to mention, and it looks like MI2 doesn´t have this function. Still looking for a GDB solution, but it looks like I have to do replaceAll with what it is returned from `data-evaluate-expression`.

**Comment by OlegKunitsyn** [comment] 2020-05-10 17:53
I like `<repeats ...>`, it's time-saving. 
Just compiled and tested on cobc 2.2. I prefer to save memory instead of searching time (Array.find vs dataStoragesByC + dataStoragesByCobol) but we may try your way. Good job, thank you!
One thing I didn't get: please put the breakpoint on line 14 of subsubsample.cbl and launch sample.cbl. I see `<nullptr>` in WS-GROUP var, don't you?

**Comment by GitMensch** [comment] 2020-05-10 17:56
> I like `<repeats ...>`, it's time-saving.

It is reasonable to keep this in for the display (especially as a tooltip when hovering over the variables in the code, when this is supported) as as it comes "for free".
But it cannot be used when the user wants to adjust the content - in this case we need to full data as-is (while there's still the issue that it is hard to display 64k+ of data...).

**Comment by brunopacheco1** [comment] 2020-05-11 08:33
> I like `<repeats ...>`, it's time-saving.
> Just compiled and tested on cobc 2.2. I prefer to save memory instead of searching time (Array.find vs dataStoragesByC + dataStoragesByCobol) but we may try your way. Good job, thank you!
> One thing I didn't get: please put the breakpoint on line 14 of subsubsample.cbl and launch sample.cbl. I see `<nullptr>` in WS-GROUP var, don't you?

@OlegKunitsyn I totally agree, it looks nice when the field was just initialized, but as soon as you insert any value, it gets awkward. For instance, if you have a data storage of size 20, 4 fields of size 5, if you insert 10000 for the first field, the GDB response is going to be `\"1\", '0' <repeats 19 times>`.

So, what do you think of replacing just the first occurrence of this `<repeats ...>`? I believe this is enough for getting the values of the fields correctly.

**Comment by brunopacheco1** [comment] 2020-05-11 08:35
BTW, I did see this nullpointer, but I didn't check it yet, I've been trying to find a solution to get and present fields values.

**Comment by brunopacheco1** [comment] 2020-05-12 22:38
Hello folks. So, I recently pushed some changes and the panel looks something like this now:

![image](https://user-images.githubusercontent.com/4491850/81752024-ec6ddf80-94b0-11ea-9ce7-04242fbee9a6.png)

There's still some work to do:
* Present numbers as numbers (including decimals when applicable);
* Present current variables vs local variables (if the variables are not present in the current stack frame GDB throws an exception);
* Add test scenarios to test the variables hierarchy parsing;
* Fix / Refactor the MI parsing methods;

**Comment by GitMensch** [comment] 2020-05-13 05:25
Thank you @brunopacheco1 for the update! Is there some "libcob/codegen" knowledge that may help you?

**Comment by brunopacheco1** [comment] 2020-05-13 07:32
@GitMensch Sure there are, About numbers, my suspects are this info should be in the attribute (part of cob_field structure), but I didn't check that yet.

**Comment by GitMensch** [comment] 2020-05-13 08:22
> my suspects are this info should be in the attribute (part of cob_field structure

Correct.

```c
static const cob_field c_1	= {4, (cob_u8_ptr)"8192", &a_3};
static const cob_field_attr a_3 =	{0x10,   4,   0, 0x1000, NULL};

/* Field attribute structure */

typedef struct __cob_field_attr {
	unsigned short		type;		/* Field type */
	unsigned short		digits;		/* Digit count */
	signed short		scale;		/* Field scale */
	unsigned short		flags;		/* Field flags */
	const cob_pic_symbol	*pic;		/* Pointer to picture string */
} cob_field_attr;

/* Field types */

#define COB_TYPE_UNKNOWN		0x00
#define COB_TYPE_GROUP			0x01U
#define COB_TYPE_BOOLEAN		0x02U

#define COB_TYPE_NUMERIC		0x10U
#define COB_TYPE_NUMERIC_DISPLAY	0x10U
#define COB_TYPE_NUMERIC_BINARY		0x11U
#define COB_TYPE_NUMERIC_PACKED		0x12U
#define COB_TYPE_NUMERIC_FLOAT		0x13U
#define COB_TYPE_NUMERIC_DOUBLE		0x14U
#define COB_TYPE_NUMERIC_L_DOUBLE	0x15U
#define COB_TYPE_NUMERIC_FP_DEC64	0x16U
#define COB_TYPE_NUMERIC_FP_DEC128	0x17U
#define COB_TYPE_NUMERIC_FP_BIN32	0x18U
#define COB_TYPE_NUMERIC_FP_BIN64	0x19U
#define COB_TYPE_NUMERIC_FP_BIN128	0x1AU
#define COB_TYPE_NUMERIC_COMP5		0x1BU

#define COB_TYPE_NUMERIC_EDITED		0x24U

#define COB_TYPE_ALNUM			0x20U
#define COB_TYPE_ALPHANUMERIC		0x21U
#define COB_TYPE_ALPHANUMERIC_ALL	0x22U
#define COB_TYPE_ALPHANUMERIC_EDITED	0x23U

#define COB_TYPE_NATIONAL		0x40U
#define COB_TYPE_NATIONAL_EDITED	0x41U

/* Field flags */

#define COB_FLAG_HAVE_SIGN		(1U << 0)	/* 0x0001 */
#define COB_FLAG_SIGN_SEPARATE		(1U << 1)	/* 0x0002 */
#define COB_FLAG_SIGN_LEADING		(1U << 2)	/* 0x0004 */
#define COB_FLAG_BLANK_ZERO		(1U << 3)	/* 0x0008 */
#define COB_FLAG_JUSTIFIED		(1U << 4)	/* 0x0010 */
#define COB_FLAG_BINARY_SWAP		(1U << 5)	/* 0x0020 */
#define COB_FLAG_REAL_BINARY		(1U << 6)	/* 0x0040 */
#define COB_FLAG_IS_POINTER		(1U << 7)	/* 0x0080 */
#define COB_FLAG_NO_SIGN_NIBBLE		(1U << 8)	/* 0x0100 */
#define COB_FLAG_IS_FP			(1U << 9)	/* 0x0200 */
#define COB_FLAG_REAL_SIGN		(1U << 10)	/* 0x0400 */
#define COB_FLAG_BINARY_TRUNC		(1U << 11)	/* 0x0800 */
#define COB_FLAG_CONSTANT		(1U << 12)	/* 0x1000 */

/* Option to check for specific flags */

#define COB_FIELD_HAVE_SIGN(f)		((f)->attr->flags & COB_FLAG_HAVE_SIGN)
#define COB_FIELD_SIGN_SEPARATE(f)	((f)->attr->flags & COB_FLAG_SIGN_SEPARATE)
#define COB_FIELD_SIGN_LEADING(f)	((f)->attr->flags & COB_FLAG_SIGN_LEADING)
#define COB_FIELD_BLANK_ZERO(f)		((f)->attr->flags & COB_FLAG_BLANK_ZERO)
#define COB_FIELD_JUSTIFIED(f)		((f)->attr->flags & COB_FLAG_JUSTIFIED)
#define COB_FIELD_BINARY_SWAP(f)	((f)->attr->flags & COB_FLAG_BINARY_SWAP)
#define COB_FIELD_REAL_BINARY(f)	((f)->attr->flags & COB_FLAG_REAL_BINARY)
#define COB_FIELD_IS_POINTER(f)		((f)->attr->flags & COB_FLAG_IS_POINTER)
#define COB_FIELD_NO_SIGN_NIBBLE(f)	((f)->attr->flags & COB_FLAG_NO_SIGN_NIBBLE)
#define COB_FIELD_IS_FP(f)		((f)->attr->flags & COB_FLAG_IS_FP)
#define COB_FIELD_REAL_SIGN(f)		((f)->attr->flags & COB_FLAG_REAL_SIGN)
#define COB_FIELD_BINARY_TRUNC(f)	((f)->attr->flags & COB_FLAG_BINARY_TRUNC)
#define COB_FIELD_CONSTANT(f)		((f)->attr->flags & COB_FLAG_CONSTANT)
```

@brunopacheco1 Does this help? Just drop a note where you need more info.

**Comment by brunopacheco1** [comment] 2020-05-13 21:02
Definitely it helps, thanks a lot.

**Comment by brunopacheco1** [comment] 2020-05-16 22:01
Hey guys, I have done most of all things I listed before, the only missing thing is presenting numbers and other data types as they should be.

I was thinking, perhaps the current state could be merged. @OlegKunitsyn Can you take a look at the changes?

**Comment by OlegKunitsyn** [comment] 2020-05-17 06:13
Well done!

**Closed by OlegKunitsyn** 2020-05-17 06:13 UTC

**Comment by GitMensch** [comment] 2020-05-17 23:15
@brunopacheco1 do you want to track the numeric field display/accept in this issue (so @OlegKunitsyn may reopen it) or in a separate issue?

**Comment by brunopacheco1** [comment] 2020-05-18 07:06
I believe it's reasonable to openning a new issue for displaying properly numeric fields.

**Comment by GitMensch** [comment] 2020-11-07 23:54
@OlegKunitsyn as both this and #30 are finished - do we still need the fields branch? GH says it is 7 commits ahead of master but I did not checked those. Otherwise it would be useful to delete the fields branch to prevent confusion.

**Comment by OlegKunitsyn** [comment] 2020-11-08 11:16
Deleted
